#743 [FEAT] 베숙트 화면 구성하기
snorose/snorose-front-react pull request #745
Opened 2024-11-29 06:07 UTC by quothraven1122

## 🎯 관련 이슈

close #743 

<br />

## 🚀 작업 내용

- 베숙트 화면 구성하기

<br />

 

## 🙋🏻‍♀️ 리뷰어가 어떤 부분에 집중해야 할까요?

- 지금 베숙트 백엔드가 dev에만 있다고 하니 리뷰할때 아마 env를 바꿔서 테스트 해야할 수도 있습니다
- 놀랍게도 베숙트 글이 공교롭게 10개밖에 없다고 합니다. 스크롤 안되어도 놀라지 마세요!

2024-11-30 13:12 UTC, haesa requested changes
메인화면에서 미로그인 상태거나 접근 권한이 없을 때 베숙트 api에서 에러가 발생하고 있습니다.
적절한 권한일 때만 호출할 수 있도록 수정해주세요!

2024-11-30 13:18 UTC, quothraven1122 commented on src/components/MainPageListItem/MainPageListItem.jsx
> +  // timeAgo를 1분마다 업데이트
베숙트에서도 글에다가 '몇분전' 달아줘야 하는데 백엔드에서는 언제 만들어졌는지만 리턴해줘서 
다른 게시판은 어떻게 했는지  확인해보니까 이 코드를 쓰더라고요 (만든 시기 -> 얼마전으로 전환)

2024-12-01 06:54 UTC, haesa approved these changes

2024-12-02 02:24 UTC, junheekim61 approved these changes
✅

2024-12-02 02:48 UTC, merged